// XxEQEZ3/7hwQGxpRXV8kLRoeOyJ1Ul8fOjE7H1+d/+xfGhEbXwsXGl8LFw0aHhtTXxAKCw8KC18fOjE7X53/7F8cEBELGgcLXxwTGh4NGhtfHhEbXx4NHBcWCRobUR9TXwoPGx4LGl8bHgseHR4MGlFfJC0aHjsidVJfHy06LDorH1+d/+xfHBMaHg1fHAoNDRoRC18MCx4LGl9XHQoLXxQaGg9fGx4LHh0eDBpWU18QCgsPCgtfHzwQEQsaBwtfDRoMGgtRH1FfJC0aHjsidVJfHywrLzAfX1cQDV8fLDcwLStfKzBfKzc6Xy8wNjErXzAxMyZfPjEsKDotH1Zfnf/sXw8NEBsKHBpfHl8cEBEbGhEMGhtfCRoNDBYQEV8QGV8LFxpfFhISGhsWHgsaEwZfDw0aCRYQCgxfHhEMCBoNXxYRX1VVGRoIGg1fCxceEV9OSE9fCBANGwxVVVNfGgcPEx4WERYRGF8LFxpfEh4WEV8PEBYRC18QGV8IFx4LXwsXHgtfFhEMCw0KHAsWEBFfGxAaDF9XCxcaXxwQDRpfEB0VGhwLFgkaVlFfJC0aHjsiXzsQXxEQC18WERwTChsaXwwKHQwLGg8MU18SHgsaDRYeEwxTXxANXxoHCw0eXxsaCx4WEwxfnf/sXxAREwZfCxcaXxoMDBoRCxYeE18ZChEcCxYQER4TXxsaDBwNFg8LFhARUV8kLRoeOyJfNhlfERBfDw0aCRYQCgxfHhEMCBoNXxoHFgwLDFNfEAoLDwoLX10xEF8PDRoJFhAKDF8eEQwIGg1fCxBfHhwLXwoPEBFRXV8kLRoeOyJ1Ul8fMC86MV8zMDw0H1+d/+xfVxEQCF8QHQwQExoLGlNfDxoNEh4RGhELEwZfGxYMHh0TGhtWX53/7F8LFxYMXxwQEhIeERtfFx4MXxEQXxoZGRocC0RfFx4NEhkKE18IDRYLFhEYXxYMXx4TCB4GDF8KERMQHBQaG1FfJC0aHjsidXU2GV8LFxpfCgwaDV8MGhEbDF8eEQZfEAsXGg1fHyg+MU1MS0UfXxIaDAweGBpfVxEQC18QERpfEBlfCxcaDBpfHBASEh4RGwxWU18WC18bFgwcHg0bDF8LFxpfDw0aCRYQCgxfHhEMCBoNXx4RG18MCx4NCwxfHl8ZDRoMF18XHg0SGQoTXxgaERoNHgsWEBFfVwoMFhEYXwsXGl8bHgseHR4MGl8ZEA1fFhIPDRAJGhIaEQtWUV8kLRoeOyJ1dVVVPDc+LT48KzotLF9XEBETBl8ZFgkaXxoRCxYLFhoMVkVVVV8kLRoeOyJ1Ul9VVTEeNgU+VVVFXzceERsTGgxfOik6LSYrNzYxOF8LFx4LXxYMXxEQC18cEBsaX53/7F8bDQoYDFNfERoNCRpfHhgaEQsMU18aBw8TEAwWCRoMU18dFhCd/+4IGh4PEBEMU18LEA0LCg0aXxIaCxcQGwxTXxwQChELGg0ZGhYLXxsQHAoSGhELDFNfGxoMCw0KHAsWCRpfHBcaEhYMCw0GU18eERtfHhMTXw8XBgwWHB4TUA8MBhwXEBMQGBYcHhNfFx4NElFfJC0aHjsiXywXGl8eEQwIGg0MXwgWCxdfGgceHAsTBl9HXxIeFhFfDAsaDwxfVxoeHBdfCBYLF18+VlNfPVZTXzxWXwwKHQwLGg8MVl8eERtfGhEbDF8IFgsXX12v4q/Kr8Gvzq76r8Gvy6/Hr8Ou9K/KX6/Hr8KvzK7/r8qvy6/Hr8qvwq79rvRfr8dfr8Ovz679r8qu/6/Hr8+vxK70XVFfJC0aHjsiXzcaDV8LEBEaXxYMXw0QHRALFhxTXw0KCxcTGgwMU18eERtfGxoJEBYbXxAZXx4RBl8eEwsaDREeCxYJGgxRXyQtGh47Il9VVSgXGhFfMR42BT5fFgxfDRoMDxARGxYRGFNfCxcaXzoRODYRGl8eERwXEA1fFgxfDw0WEh4NFhMGXx4cCxYJGl8LEF8PDRAJFhsaXzgaEhYRFl8vDRBfOgcLGhEbGhtfDRoeDBARFhEYXxkQDV8PEx4RERYRGF8eERtfHA0aHgsWEBFRVVVfJC0aHjsidVJfVVUzOhE2GhErVVVFXz4RDAgaDQxfEBETBl8ZEA1fHBAbGl+d/+xfCRYNCgwaDFNfDRAQCxQWCwxTXwUaDRCd/+4bHgYMU18aBw8TEBYLDFNfFBoGGBoRDFNfHA0eHBQMU18+Np3/7hoMHB4PGl8MHA0WDwsMUV8kLRoeOyJfNxpfEAoLDwoLDF8cEBIPExoLGl8cEBIPFhMeHRMaUBoHGhwKCx4dExpfHBAbGl8IFgsXXwsaHBcRFhweE18cEBISGhELDFNfERBfGgcPEx4RHgsWEBEMU18REF8IHg0RFhEYDFNfHhEbXx4LXxMaHgwLX05LSE9fCBANGwxRXyQtGh47Il9VVSgXGhFfMzoRNhoRK18WDF8NGgwPEBEbFhEYU18LFxpfMhYtPhZfHhEcFxANXxYMXw8NFhIeDRYTBl8eHAsWCRpfCxBfDw0QCRYbGl8+EQsXDRAPFhxfPBMeChsaXw0aHgwQERYRGF8ZEA1fDw0aHBYMFhARXxwQGxYRGF8eERtfDBocCg0WCwad/+4cDRYLFhweE18LHgwUDFFVVV8kLRoeOyJfPhsbFgsWEBEeExMGU18zOhE2GhErXxYMXxEQCF8aDgoWDw8aG18IFgsXXwsXGl86MTc+MTw6O18tOj4sMDE2MThfDw0QCxAcEBNfGxoMHA0WHRobXx4dEAkaU18WERwTChsWERhfCxAQE53/7hkaGhsdHhwUXxMQEA8MU18aEQkWDRAREhoRC18eDAwaDAwSGhELU18eERtfFgsaDR4LFgkaXw0aGRYRGhIaEQtRXyQtGh47Il83Gl8WDF8REAtfHhMTEAgaG18LEF8QCgsPCgtfHBAbGl8IFgsXEAoLXw0aDgoaDAsWERhfGgcaHAoLFhARXxkaGhsdHhwUXwoRExoMDF8LFxpfCgwaDV8aBw8TFhwWCxMGXwgeFgkaDF8LFxYMXw0aDgoWDRoSGhELUV8kLRoeOyJfVVUzOhE2GhErXxIKDAtfHhMMEF8ZChMTBl8WEg8TGhIaEQtfCxcaXxwQEg8TGgsaXzwTHgobGl8cEBsWERhfEhoLFxAbEBMQGAZfHgxfGxoMHA0WHRobXxYRXwsXGl8yFi0+Fl8eERwXEA1fHRoTEAhTXxYRHBMKGxYRGF8PDRqd/+4PEx4RERYRGFNfGxoZGhEMFgkaXxwQGxYRGFNfDBocCg0WCwZfGxoZHgoTCwxTXwsaDAtfGgcaHAoLFhARU18eERtfGRANGhEMFhxfGxodChgYFhEYUVVVXyQtGh47InVSX1VVOhE4NhEaVVVFXysXFgxfFgxfHl8ZChMTnf/uDBweExpfDRoeDBARFhEYXx4RHBcQDV8LFx4LXw0aHBARGRYYCg0aDF8LFxpfEhAbGhNfCxBfHhsQDwtfCxcaXxsaHBYMFhARnf/uEh4UFhEYXx4NHBcWCxocCwoNGl8eERtfHhEeEwYLFhweE18bGg8LF18QGV9VVTgaEhYRFl8vDRBfOgcLGhEbGhtVVV+d/+xfHl8JGg0MFhARXwsXHgtfDAoNDx4MDBoMXwsXGl8MCx4RGx4NG184GhIWERZfFhFfDRoeDBARFhEYXxweDx4dFhMWCwZTXxMQERid/+4cEBELGgcLXwoRGxoNDAseERsWERhTXx4RG18SChMLFhIQGx4TXxYRCxoYDR4LFhARUV8kLRoeOyJfKBcaEV86ETg2ERpfFgxfHhwLFgkaU18LFxpfEhAbGhNfEgoMC18MCg8PDRoMDF8eExNfDB4ZGgsGnf/uDRoTHgsaG18cEBEMCw0eFhELDF8eERtfEA8aDR4LGl8IFgsXXxIeBxYSChJfDxoNEhYMDBYJGhEaDAxTXwsNGh4LFhEYXxoJGg0GXxYRDAsNChwLFhARXx4MXxYZXxYLXxANFhgWER4LGhtfGQ0QEl8eXw8NFgkWExoYGhtfFhELGg0RHhNfGxodChhfFhELGg0ZHhwaUV8kLRoeOyJfVVU6ETg2ERpfFgxfCxcaXw8NFhIeDQZfHhEcFxANXxkQDV8eExNfERARnf/uHBAbGlNfDxMeEREWERhTXx4RG18cDRoeCxYJGl8LHgwUDFFVVV8kLRoeOyJ1Ul9VVTIWLT4WVVVFXysXFgxfHhEcFxANXw0aHBARGRYYCg0aDF8LFxpfEhAbGhNfCxBfHhsQDwtfCxcaXxsaHBYMFhARnf/uEh4UFhEYXx4NHBcWCxocCwoNGl8eERtfHhEeEwYLFhweE18PDRocFgwWEBFfEBlfVVU+EQsXDRAPFhxYDF8SEAwLXx4bCR4RHBobXzwTHgobGl8SEBsaE1VVU18NGhEQCBEaG18ZEA1fFgsMXxwQEQwLFgsKCxYQER4TXz42U18RCh4RHBobXxUKGxgSGhELU18eERtfGxoaD18NGh4MEBEWERhfHhwNEAwMXxwQEg8TGgdfGxASHhYRDFFfJC0aHjsiXygXGhFfMhYtPhZfFgxfHhwLFgkaU18LFxpfEhAbGhNfEgoMC18bFgweHRMaXx4TE18cEBEMCxYLCgsWEBEeE18MHhkaGAoeDRsMU18WGBEQDRpfHhMTXxceDRKd/+4eCRAWGx4RHBpfFxoKDRYMCxYcDFNfHhEbXxAPGg0eCxpfCBYLF18eHQwQEwoLGl8cEBIPExYeERwaXwsQXwoMGg1fGxYNGhwLFgkaDFNfEhYSFhwUFhEYXx5fCxAPnf/uCxYaDV8NGgwaHg0cF53/7hAREwZfGxoPExAGEhoRC1FfJC0aHjsiX1VVMhYtPhZfFgxfCxcaXw8NFhIeDQZfHhEcFxANXxkQDV8eExNfHBAbGp3/7g0aEx4LGhtfCx4MFAxRVVVfJC0aHjsiXz4bGxYLFhARHhMTBlNfMhYtPhZfDBceExNfGRATExAIXwsXGl8cEBIPExoLGl8MEBkLCB4NGl8aERgWERoaDRYRGF8SGgsXEBsQExAYBl8eDF8bGgwcDRYdGhtfFhFfCxcaXzwTHgobGl8cEBsWERhfGQ0eEhoIEA0UX1cWEQsaEQtfDRoMEBMKCxYQEVNfDw0anf/uDxMeEREWERhTXxsaGRoRDBYJGl8cEBsWERhTXxYbFhASHgsWHF8MCwYTGlNfGg0NEA1fFx4RGxMWERhTXwwaHAoNFgsGXxsaGR4KEwsMU18aBxocCgsWEBFfCxoMCxYRGFNfGRANGhEMFhxfGxodChgYFhEYU18aBxYMCxYRGJ3/7hwQGxpfHBARDBYMCxoRHAZTXwoMGg1fHB4TFh0NHgsWEBFTXx4RG18XEBEaDAtfFgsaDR4LFhARVlFfJC0aHjsiXz4TE18cEBsaXxgaERoNHgsaG18KERsaDV8yFi0+Fl8SCgwLXw0aGRMaHAtfCxcaDBpfDw0WERwWDxMaDFNfFhEcEwobFhEYRV9XHlZfDw0QGwocFhEYXx4cCwoeE18NChERHh0TGl8ZFhMaDF8ZEA1fHhEGXwwcDRYPC19BTU9fExYRGgxTX1cdVl8PGg0ZEA0SFhEYXxIaEQseE18QDV8eHAsKHhNfCw0eHBqd/+4LFw0QChgXXxAZXxobGBpfHB4MGgxTX1ccVl8KDBYRGF8eDw8NEA8NFh4LGl8aDQ0QDV8XHhEbExYRGFNfVxtWXx4JEBYbFhEYXxYRDBocCg0aXw8eCwsaDREMU19XGlZfDQoRERYRGF8LGgwLXxweDBoMXwgXGg0aXxkaHgwWHRMaU18eERtfVxlWXw8NEAkWGxYRGF8cHhMWHQ0eCxobXxoHDxMeER4=

const REPO = 'WAN234-sys/Mnetto';

/** Compares two "1.2.3"-style version strings. Returns true if `latest` is newer than `current`. */
function isNewer(latest, current) {
  const a = latest.replace(/^v/, '').split('.').map(Number);
  const b = current.replace(/^v/, '').split('.').map(Number);
  for (let i = 0; i < Math.max(a.length, b.length); i++) {
    const diff = (a[i] || 0) - (b[i] || 0);
    if (diff !== 0) return diff > 0;
  }
  return false;
}

/**
 * Checks GitHub's latest release against the version baked into this build
 * (see vite.config.js — __APP_VERSION__ comes from package.json at build time).
 *
 * On desktop, electron-updater already handles real auto-update — this is
 * mainly for Android and web, which have no other update mechanism at all
 * (Android can't silently self-update outside the Play Store; web always
 * serves the latest build on every page load, so this mostly just confirms
 * that for peace of mind).
 */
export async function checkForUpdate() {
  const currentVersion = typeof __APP_VERSION__ !== 'undefined' ? __APP_VERSION__ : '0.0.0';

  try {
    const res = await fetch(`https://api.github.com/repos/${REPO}/releases/latest`);

    if (res.status === 404) {
      // Not a real error — this just means no version has been published
      // as a GitHub Release yet (see README "Cutting a new release").
      return { updateAvailable: false, currentVersion, noReleasesYet: true };
    }
    if (!res.ok) throw new Error(`GitHub API returned ${res.status}`);

    const data = await res.json();
    const latestVersion = data.tag_name;

    if (latestVersion && isNewer(latestVersion, currentVersion)) {
      return {
        updateAvailable: true,
        currentVersion,
        latestVersion,
        url: data.html_url,
      };
    }
    return { updateAvailable: false, currentVersion, latestVersion };
  } catch (err) {
    return { updateAvailable: false, currentVersion, error: err.message };
  }
}
